### PR TITLE
Create install rules

### PR DESCRIPTION
**Pull request by jim-v**
This PR adds install rules to `CMakeLists.txt` so that `catkin_make install` works.  It creates subdirectories `param` and `launch`.

### CODE REVIEW

**Review by rohbotics — APPROVED** [review]
Seems reasonable to me, @mjstn should review as well.

**Review by mjstn — APPROVED** [review]
I did not understand why = did not work for the README so thanks for changing format for the titles.    

I'm not up on the actual functional changes but if you see that they work then I approve.   Specifically I am not sure why param was needed in the path because maybe you moved bt_joystick.yaml into folder param.  But fiducial_follow does not use that convention.  Anyway, it's ok with me if you tested it.

**Comment by jim-v** [comment]
fiducial_follow doesn't have any param or launch files.  They don't have to be in separate directories, but while I was adding the CMakeLists.txt rules to installed them, I created the directories.

**Comment by jim-v** [comment]
@mjstn There are some things in `package.xml` that should be filled out, like maintainer email address and license.

**Comment by mjstn** [comment]
Yes thats fine.  Again, I'm not up on the clean installation rules and 
so on.
I saw the aruco yaml file and just did my file in that placement is all.

Thanks for moving things around and cleaning up Jim.

The usage of = signs is because for last 2 years I have been doing for 
Zizmos my docs in the wiki part of github and was just 'habit'

Mark

**Pull request merged**
